---
- name: Setup Tasks
  hosts: localhost
  become: true
  tasks:
    - name: Fix File Permissions
      ansible.builtin.file:
        path: "../traefik/letsencrypt/acme.json"
        mode: '0600'

    - name: Set DNSStubListener
      ini_file:
        path: /etc/systemd/resolved.conf
        section: Resolve
        option: DNSStubListener
        value: "no"
        no_extra_spaces: yes

    - name: Set DNS Servers
      ini_file:
        path: /etc/systemd/resolved.conf
        section: Resolve
        option: DNS
        value: 1.1.1.1
        no_extra_spaces: yes
    
    - name: Delete existing /etc/resolv.conf file or link
      file: 
        path: /etc/resolv.conf
        state: absent
    
    - name: Creating a symlink
      ansible.builtin.file:
        src: /run/systemd/resolve/resolv.conf
        dest: /etc/resolv.conf
        state: link
 
    - name: Restart systemd-resolved
      systemd:
        name: systemd-resolved
        state: restarted
        enabled: yes
        masked: no
